In [2]:
import pandas as pd

df = pd.read_csv("../dataset/student-mat.csv", sep=";")

df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [3]:
import pandas as pd
import numpy as np

df = pd.read_csv("../dataset/student-mat.csv", sep=";")

print(df.shape)
df.head()

(395, 33)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [4]:
df.info

<bound method DataFrame.info of     school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher
1       GP   F   17       U     GT3       T     1     1   at_home     other
2       GP   F   15       U     LE3       T     1     1   at_home     other
3       GP   F   15       U     GT3       T     4     2    health  services
4       GP   F   16       U     GT3       T     3     3     other     other
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...
390     MS   M   20       U     LE3       A     2     2  services  services
391     MS   M   17       U     LE3       T     3     1  services  services
392     MS   M   21       R     GT3       T     1     1     other     other
393     MS   M   18       R     LE3       T     3     2  services     other
394     MS   M   19       U     LE3       T     1     1     other   at_home

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
0    ...      4        3      4     1     1      3        6   5   6   6
1    ...      5        3      3     1     1      3        4   5   5   6
2    ...      4        3      2     2     3      3       10   7   8  10
3    ...      3        2      2     1     1      5        2  15  14  15
4    ...      4        3      2     1     2      5        4   6  10  10
..   ...    ...      ...    ...   ...   ...    ...      ...  ..  ..  ..
390  ...      5        5      4     4     5      4       11   9   9   9
391  ...      2        4      5     3     4      2        3  14  16  16
392  ...      5        5      3     3     3      3        3  10   8   7
393  ...      4        4      1     3     4      5        0  11  12  10
394  ...      3        2      3     3     3      5        5   8   9   9

[395 rows x 33 columns]>

In [5]:
df.columns.tolist()

['school',
 'sex',
 'age',
 'address',
 'famsize',
 'Pstatus',
 'Medu',
 'Fedu',
 'Mjob',
 'Fjob',
 'reason',
 'guardian',
 'traveltime',
 'studytime',
 'failures',
 'schoolsup',
 'famsup',
 'paid',
 'activities',
 'nursery',
 'higher',
 'internet',
 'romantic',
 'famrel',
 'freetime',
 'goout',
 'Dalc',
 'Walc',
 'health',
 'absences',
 'G1',
 'G2',
 'G3']

In [6]:
df.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000
mean,16.696203,2.749367,2.521519,1.448101,2.035443,0.334177,3.944304,3.235443,3.108861,1.481013,2.291139,3.554430,5.708861,10.908861,10.713924,10.415190
std,1.276043,1.094735,1.088201,0.697505,0.839240,0.743651,0.896659,0.998862,1.113278,0.890741,1.287897,1.390303,8.003096,3.319195,3.761505,4.581443
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,3.000000,0.000000,0.000000
25%,16.000000,2.000000,2.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000,8.000000,9.000000,8.000000
50%,17.000000,3.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,4.000000,11.000000,11.000000,11.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,8.000000,13.000000,13.000000,14.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000,19.000000,19.000000,20.000000

In [7]:
df.isnull().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

In [8]:
print("Total missing values:", df.isnull().sum().sum())

Total missing values: 0

In [9]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [10]:
categorical_columns = df.select_dtypes(
    include=["object"]
).columns.tolist()

numerical_columns = df.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

print("Categorical columns:")
print(categorical_columns)

print("\nNumerical columns:")
print(numerical_columns)

Categorical columns:
['school', 'sex', 'address', 'famsize', 'Pstatus', 'Mjob', 'Fjob', 'reason', 'guardian', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'romantic']

Numerical columns:
['age', 'Medu', 'Fedu', 'traveltime', 'studytime', 'failures', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences', 'G1', 'G2', 'G3']

Regression Target

In [11]:
y_regression = df["G3"]

Classification Target

In [12]:
df["result"] = (df["G3"] >= 10).astype(int)

In [13]:
print(df["result"].value_counts())

result
1    265
0    130
Name: count, dtype: int64

In [14]:
X = df.drop(["G3", "result"], axis=1)

y_regression = df["G3"]

y_classification = df["result"]

print("X shape:", X.shape)
print("Regression target shape:", y_regression.shape)
print("Classification target shape:", y_classification.shape)

X shape: (395, 32)
Regression target shape: (395,)
Classification target shape: (395,)

In [15]:
print("G1 in X:", "G1" in X.columns)
print("G2 in X:", "G2" in X.columns)
print("G3 in X:", "G3" in X.columns)
print("result in X:", "result" in X.columns)

G1 in X: True
G2 in X: True
G3 in X: False
result in X: False

In [16]:
X = df.drop("G3", axis=1)

In [17]:
y_regression = df["G3"]

y_classification = df["result"]

In [18]:
print(df["age"].min(), df["age"].max())
print(df["G1"].min(), df["G1"].max())
print(df["G2"].min(), df["G2"].max())
print(df["G3"].min(), df["G3"].max())
print(df["absences"].min(), df["absences"].max())

15 22
3 19
0 19
0 20
0 75

In [19]:
%pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\shree\appdata\local\programs\python\python311\lib\site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\shree\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (2.2.6)
Requirement already satisfied: scipy>=1.10.0 in c:\users\shree\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.4.0 in c:\users\shree\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\shree\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (2.15.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\users\shree\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: cloudpickle>=3.0 in c:\users\shree\appdata\local\programs\python\python311\lib\site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [20]:
# Create the feature lists with the names used in preprocessing

categorical_features = X.select_dtypes(
    include=["object"]
).columns.tolist()

numerical_features = X.select_dtypes(
    exclude=["object"]
).columns.tolist()

print("Categorical features:", categorical_features)
print("Numerical features:", numerical_features)

Categorical features: ['school', 'sex', 'address', 'famsize', 'Pstatus', 'Mjob', 'Fjob', 'reason', 'guardian', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'romantic']
Numerical features: ['age', 'Medu', 'Fedu', 'traveltime', 'studytime', 'failures', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences', 'G1', 'G2', 'result']

In [21]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numerical_features),
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features)
    ]
)

print("Preprocessing pipeline created successfully!")

Preprocessing pipeline created successfully!

In [22]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_reg_train, y_reg_test, y_cls_train, y_cls_test = train_test_split(
    X,
    y_regression,
    y_classification,
    test_size=0.2,
    random_state=42,
    stratify=y_classification
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)
print("Regression training target:", y_reg_train.shape)
print("Classification training target:", y_cls_train.shape)

Training data: (316, 33)
Testing data: (79, 33)
Regression training target: (316,)
Classification training target: (316,)

In [23]:
# Fit preprocessing only on training data
X_train_processed = preprocessor.fit_transform(X_train)

# Transform test data using the same preprocessing
X_test_processed = preprocessor.transform(X_test)

print("Processed training data:", X_train_processed.shape)
print("Processed testing data:", X_test_processed.shape)

Processed training data: (316, 59)
Processed testing data: (79, 59)

In [24]:
import scipy.sparse as sp

# Convert processed data to dense DataFrames
X_train_df = pd.DataFrame(
    X_train_processed.toarray() if sp.issparse(X_train_processed) else X_train_processed
)

X_test_df = pd.DataFrame(
    X_test_processed.toarray() if sp.issparse(X_test_processed) else X_test_processed
)

# Save processed data
X_train_df.to_csv("../dataset/X_train_processed.csv", index=False)
X_test_df.to_csv("../dataset/X_test_processed.csv", index=False)

y_reg_train.to_csv("../dataset/y_reg_train.csv", index=False)
y_reg_test.to_csv("../dataset/y_reg_test.csv", index=False)

y_cls_train.to_csv("../dataset/y_cls_train.csv", index=False)
y_cls_test.to_csv("../dataset/y_cls_test.csv", index=False)

print("Processed datasets saved successfully!")

Processed datasets saved successfully!

In [25]:
print("Original dataset:", df.shape)
print("Training features:", X_train.shape)
print("Testing features:", X_test.shape)
print("Processed training:", X_train_processed.shape)
print("Processed testing:", X_test_processed.shape)

print("\nMissing values:", df.isnull().sum().sum())
print("Duplicate rows:", df.duplicated().sum())

print("\nRegression target range:")
print(y_regression.min(), "to", y_regression.max())

print("\nClassification target:")
print(y_classification.value_counts())

Original dataset: (395, 34)
Training features: (316, 33)
Testing features: (79, 33)
Processed training: (316, 59)
Processed testing: (79, 59)

Missing values: 0
Duplicate rows: 0

Regression target range:
0 to 20

Classification target:
result
1    265
0    130
Name: count, dtype: int64

In [26]:
import joblib

joblib.dump(
    preprocessor,
    "../models/preprocessor.pkl"
)

print("Preprocessor saved successfully!")

Preprocessor saved successfully!

In [27]:
import pandas as pd

X_train = pd.read_csv("../dataset/X_train_processed.csv")
X_test = pd.read_csv("../dataset/X_test_processed.csv")

y_cls_train = pd.read_csv("../dataset/y_cls_train.csv").squeeze()
y_cls_test = pd.read_csv("../dataset/y_cls_test.csv").squeeze()

y_reg_train = pd.read_csv("../dataset/y_reg_train.csv").squeeze()
y_reg_test = pd.read_csv("../dataset/y_reg_test.csv").squeeze()

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)

print("y_cls_train:", y_cls_train.shape)
print("y_cls_test:", y_cls_test.shape)

print("y_reg_train:", y_reg_train.shape)
print("y_reg_test:", y_reg_test.shape)

print("\nClassification training targets:")
print(y_cls_train.value_counts())

print("\nRegression target range:")
print(y_reg_train.min(), "to", y_reg_train.max())

X_train: (316, 59)
X_test: (79, 59)
y_cls_train: (316,)
y_cls_test: (79,)
y_reg_train: (316,)
y_reg_test: (79,)

Classification training targets:
result
1    212
0    104
Name: count, dtype: int64

Regression target range:
0 to 20

In [28]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Create model
lr_model = LogisticRegression(max_iter=1000, random_state=42)

# Train model
lr_model.fit(X_train, y_cls_train)

# Predict
y_pred_lr = lr_model.predict(X_test)

# Evaluation
print("Logistic Regression Results")
print("---------------------------")
print("Accuracy :", accuracy_score(y_cls_test, y_pred_lr))
print("Precision:", precision_score(y_cls_test, y_pred_lr))
print("Recall   :", recall_score(y_cls_test, y_pred_lr))
print("F1 Score :", f1_score(y_cls_test, y_pred_lr))

print("\nConfusion Matrix:")
print(confusion_matrix(y_cls_test, y_pred_lr))

Logistic Regression Results
---------------------------
Accuracy : 1.0
Precision: 1.0
Recall   : 1.0
F1 Score : 1.0

Confusion Matrix:
[[26  0]
 [ 0 53]]

In [29]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Create model
dt_model = DecisionTreeClassifier(random_state=42)

# Train model
dt_model.fit(X_train, y_cls_train)

# Predict
y_pred_dt = dt_model.predict(X_test)

# Evaluation
print("Decision Tree Results")
print("--------------------")
print("Accuracy :", accuracy_score(y_cls_test, y_pred_dt))
print("Precision:", precision_score(y_cls_test, y_pred_dt))
print("Recall   :", recall_score(y_cls_test, y_pred_dt))
print("F1 Score :", f1_score(y_cls_test, y_pred_dt))

print("\nConfusion Matrix:")
print(confusion_matrix(y_cls_test, y_pred_dt))

Decision Tree Results
--------------------
Accuracy : 1.0
Precision: 1.0
Recall   : 1.0
F1 Score : 1.0

Confusion Matrix:
[[26  0]
 [ 0 53]]

In [30]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Create model
rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

# Train model
rf_model.fit(X_train, y_cls_train)

# Predict
y_pred_rf = rf_model.predict(X_test)

# Evaluation
print("Random Forest Results")
print("---------------------")
print("Accuracy :", accuracy_score(y_cls_test, y_pred_rf))
print("Precision:", precision_score(y_cls_test, y_pred_rf))
print("Recall   :", recall_score(y_cls_test, y_pred_rf))
print("F1 Score :", f1_score(y_cls_test, y_pred_rf))

print("\nConfusion Matrix:")
print(confusion_matrix(y_cls_test, y_pred_rf))

Random Forest Results
---------------------
Accuracy : 1.0
Precision: 1.0
Recall   : 1.0
F1 Score : 1.0

Confusion Matrix:
[[26  0]
 [ 0 53]]

In [31]:
import xgboost
print("XGBoost version:", xgboost.__version__)

XGBoost version: 3.2.0

In [32]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Create model
xgb_model = XGBClassifier(
    n_estimators=100,
    max_depth=3,
    learning_rate=0.1,
    random_state=42,
    eval_metric="logloss"
)

# Train model
xgb_model.fit(X_train, y_cls_train)

# Predict
y_pred_xgb = xgb_model.predict(X_test)

# Evaluation
print("XGBoost Results")
print("----------------")
print("Accuracy :", accuracy_score(y_cls_test, y_pred_xgb))
print("Precision:", precision_score(y_cls_test, y_pred_xgb))
print("Recall   :", recall_score(y_cls_test, y_pred_xgb))
print("F1 Score :", f1_score(y_cls_test, y_pred_xgb))

print("\nConfusion Matrix:")
print(confusion_matrix(y_cls_test, y_pred_xgb))

XGBoost Results
----------------
Accuracy : 1.0
Precision: 1.0
Recall   : 1.0
F1 Score : 1.0

Confusion Matrix:
[[26  0]
 [ 0 53]]

In [33]:
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

print("\nColumns containing target-like names:")
print([col for col in X_train.columns if "G3" in str(col) or "result" in str(col).lower()])

print("\nFirst 10 feature columns:")
print(X_train.columns[:10].tolist())

X_train shape: (316, 59)
X_test shape: (79, 59)

Columns containing target-like names:
[]

First 10 feature columns:
['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [34]:
# Check original dataset
df_check = pd.read_csv("../dataset/student-mat.csv", sep=";")

print("Original dataset shape:", df_check.shape)

# Create result exactly as in our project
df_check["result"] = (df_check["G3"] >= 10).astype(int)

# Check target relationship
print("\nG3 and result:")
print(df_check[["G3", "result"]].head(20))

print("\nResult distribution:")
print(df_check["result"].value_counts())

print("\nG3 distribution:")
print(df_check["G3"].value_counts().sort_index())

Original dataset shape: (395, 33)

G3 and result:
    G3  result
0    6       0
1    6       0
2   10       1
3   15       1
4   10       1
5   15       1
6   11       1
7    6       0
8   19       1
9   15       1
10   9       0
11  12       1
12  14       1
13  11       1
14  16       1
15  14       1
16  14       1
17  10       1
18   5       0
19  10       1

Result distribution:
result
1    265
0    130
Name: count, dtype: int64

G3 distribution:
G3
0     38
4      1
5      7
6     15
7      9
8     32
9     28
10    56
11    47
12    31
13    31
14    27
15    33
16    16
17     6
18    12
19     5
20     1
Name: count, dtype: int64

In [35]:
# Check whether processed features contain G3 information indirectly

print("G3 values:")
print(df_check["G3"].values[:20])

print("\nResult values:")
print(df_check["result"].values[:20])

print("\nProcessed training data:")
print(X_train.iloc[:5, :10])

G3 values:
[ 6  6 10 15 10 15 11  6 19 15  9 12 14 11 16 14 14 10  5 10]

Result values:
[0 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 0 1]

Processed training data:
          0         1         2         3         4         5         6  \
0 -1.305332  1.135587  0.462701  0.722867  2.386735 -0.442589 -2.091898
1 -0.524111 -0.667656 -1.388103  2.115708 -1.262660 -0.442589  0.093357
2 -1.305332 -1.569278 -1.388103  2.115708 -1.262660 -0.442589  0.093357
3  1.819554  0.233965 -0.462701 -0.669974 -1.262660  3.553358  0.093357
4  1.038332  1.135587  1.388103  2.115708 -1.262660 -0.442589  0.093357

          7         8         9
0 -1.272747 -1.038594 -0.554434
1 -0.269784 -0.136957 -0.554434
2 -0.269784 -0.136957 -0.554434
3  1.736141  0.764679 -0.554434
4  0.733178 -0.136957  0.513866

In [36]:
# Check whether training and testing data overlap

train_rows = set(map(tuple, X_train.values))
test_rows = set(map(tuple, X_test.values))

print("Overlapping rows:", len(train_rows.intersection(test_rows)))

Overlapping rows: 0

In [37]:
classification_results = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Decision Tree",
        "Random Forest",
        "XGBoost"
    ],
    "Accuracy": [
        accuracy_score(y_cls_test, y_pred_lr),
        accuracy_score(y_cls_test, y_pred_dt),
        accuracy_score(y_cls_test, y_pred_rf),
        accuracy_score(y_cls_test, y_pred_xgb)
    ],
    "Precision": [
        precision_score(y_cls_test, y_pred_lr),
        precision_score(y_cls_test, y_pred_dt),
        precision_score(y_cls_test, y_pred_rf),
        precision_score(y_cls_test, y_pred_xgb)
    ],
    "Recall": [
        recall_score(y_cls_test, y_pred_lr),
        recall_score(y_cls_test, y_pred_dt),
        recall_score(y_cls_test, y_pred_rf),
        recall_score(y_cls_test, y_pred_xgb)
    ],
    "F1 Score": [
        f1_score(y_cls_test, y_pred_lr),
        f1_score(y_cls_test, y_pred_dt),
        f1_score(y_cls_test, y_pred_rf),
        f1_score(y_cls_test, y_pred_xgb)
    ]
})

print(classification_results.round(4))

                 Model  Accuracy  Precision  Recall  F1 Score
0  Logistic Regression       1.0        1.0     1.0       1.0
1        Decision Tree       1.0        1.0     1.0       1.0
2        Random Forest       1.0        1.0     1.0       1.0
3              XGBoost       1.0        1.0     1.0       1.0

In [38]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Create model
lr_reg_model = LinearRegression()

# Train model
lr_reg_model.fit(X_train, y_reg_train)

# Predict
y_pred_lr_reg = lr_reg_model.predict(X_test)

# Evaluation
mae = mean_absolute_error(y_reg_test, y_pred_lr_reg)
mse = mean_squared_error(y_reg_test, y_pred_lr_reg)
rmse = np.sqrt(mse)
r2 = r2_score(y_reg_test, y_pred_lr_reg)

print("Linear Regression Results")
print("-------------------------")
print("MAE :", mae)
print("MSE :", mse)
print("RMSE:", rmse)
print("R²  :", r2)

Linear Regression Results
-------------------------
MAE : 1.4080856278457174
MSE : 3.82166429429283
RMSE: 1.9549077457242912
R²  : 0.809712571518872

In [39]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Create model
dt_reg_model = DecisionTreeRegressor(random_state=42)

# Train model
dt_reg_model.fit(X_train, y_reg_train)

# Predict
y_pred_dt_reg = dt_reg_model.predict(X_test)

# Evaluation
mae = mean_absolute_error(y_reg_test, y_pred_dt_reg)
mse = mean_squared_error(y_reg_test, y_pred_dt_reg)
rmse = np.sqrt(mse)
r2 = r2_score(y_reg_test, y_pred_dt_reg)

print("Decision Tree Regression Results")
print("--------------------------------")
print("MAE :", mae)
print("MSE :", mse)
print("RMSE:", rmse)
print("R²  :", r2)

Decision Tree Regression Results
--------------------------------
MAE : 0.9240506329113924
MSE : 3.151898734177215
RMSE: 1.7753587621033713
R²  : 0.8430613840532304

In [40]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Create model
rf_reg_model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

# Train model
rf_reg_model.fit(X_train, y_reg_train)

# Predict
y_pred_rf_reg = rf_reg_model.predict(X_test)

# Evaluation
mae = mean_absolute_error(y_reg_test, y_pred_rf_reg)
mse = mean_squared_error(y_reg_test, y_pred_rf_reg)
rmse = np.sqrt(mse)
r2 = r2_score(y_reg_test, y_pred_rf_reg)

print("Random Forest Regression Results")
print("---------------------------------")
print("MAE :", mae)
print("MSE :", mse)
print("RMSE:", rmse)
print("R²  :", r2)

Random Forest Regression Results
---------------------------------
MAE : 0.809620253164557
MSE : 1.7645848101265829
RMSE: 1.3283767575980028
R²  : 0.9121381994862057

In [41]:
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Create model
xgb_reg_model = XGBRegressor(
    n_estimators=100,
    max_depth=3,
    learning_rate=0.1,
    random_state=42,
    objective="reg:squarederror"
)

# Train model
xgb_reg_model.fit(X_train, y_reg_train)

# Predict
y_pred_xgb_reg = xgb_reg_model.predict(X_test)

# Evaluation
mae = mean_absolute_error(y_reg_test, y_pred_xgb_reg)
mse = mean_squared_error(y_reg_test, y_pred_xgb_reg)
rmse = np.sqrt(mse)
r2 = r2_score(y_reg_test, y_pred_xgb_reg)

print("XGBoost Regression Results")
print("--------------------------")
print("MAE :", mae)
print("MSE :", mse)
print("RMSE:", rmse)
print("R²  :", r2)

XGBoost Regression Results
--------------------------
MAE : 0.8534678220748901
MSE : 1.6850234270095825
RMSE: 1.2980845222902793
R²  : 0.9160997271537781

In [42]:
import pandas as pd

regression_results = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Decision Tree",
        "Random Forest",
        "XGBoost"
    ],
    "MAE": [
        1.4081,
        0.9241,
        0.8096,
        0.8535
    ],
    "MSE": [
        3.8217,
        3.1519,
        1.7646,
        1.6850
    ],
    "RMSE": [
        1.9549,
        1.7754,
        1.3284,
        1.2981
    ],
    "R2": [
        0.8097,
        0.8431,
        0.9121,
        0.9161
    ]
})

print(regression_results)

               Model     MAE     MSE    RMSE      R2
0  Linear Regression  1.4081  3.8217  1.9549  0.8097
1      Decision Tree  0.9241  3.1519  1.7754  0.8431
2      Random Forest  0.8096  1.7646  1.3284  0.9121
3            XGBoost  0.8535  1.6850  1.2981  0.9161

In [43]:
from sklearn.model_selection import GridSearchCV
from xgboost import XGBRegressor

xgb_tune = XGBRegressor(
    random_state=42,
    objective="reg:squarederror"
)

param_grid = {
    "n_estimators": [100, 200],
    "max_depth": [2, 3, 4],
    "learning_rate": [0.05, 0.1],
    "subsample": [0.8, 1.0]
}

grid_search = GridSearchCV(
    estimator=xgb_tune,
    param_grid=param_grid,
    cv=5,
    scoring="neg_mean_squared_error",
    n_jobs=-1
)

grid_search.fit(X_train, y_reg_train)

print("Best Parameters:")
print(grid_search.best_params_)

print("\nBest CV Score:")
print(-grid_search.best_score_)

Best Parameters:
{'learning_rate': 0.05, 'max_depth': 2, 'n_estimators': 100, 'subsample': 0.8}

Best CV Score:
2.0404812335968017

In [44]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

best_xgb_reg = grid_search.best_estimator_

y_pred_tuned = best_xgb_reg.predict(X_test)

mae = mean_absolute_error(y_reg_test, y_pred_tuned)
mse = mean_squared_error(y_reg_test, y_pred_tuned)
rmse = np.sqrt(mse)
r2 = r2_score(y_reg_test, y_pred_tuned)

print("Tuned XGBoost Regression Results")
print("--------------------------------")
print("MAE :", mae)
print("MSE :", mse)
print("RMSE:", rmse)
print("R²  :", r2)

Tuned XGBoost Regression Results
--------------------------------
MAE : 0.8245329856872559
MSE : 1.638594627380371
RMSE: 1.2800760240627784
R²  : 0.9184114933013916

In [45]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor

rf_tune = RandomForestRegressor(
    random_state=42
)

param_grid_rf = {
    "n_estimators": [100, 200],
    "max_depth": [None, 5, 10],
    "min_samples_split": [2, 5],
    "min_samples_leaf": [1, 2]
}

grid_search_rf = GridSearchCV(
    estimator=rf_tune,
    param_grid=param_grid_rf,
    cv=5,
    scoring="neg_mean_squared_error",
    n_jobs=-1
)

grid_search_rf.fit(X_train, y_reg_train)

print("Best Random Forest Parameters:")
print(grid_search_rf.best_params_)

print("\nBest CV Score:")
print(-grid_search_rf.best_score_)

Best Random Forest Parameters:
{'max_depth': 5, 'min_samples_leaf': 2, 'min_samples_split': 5, 'n_estimators': 100}

Best CV Score:
1.9433501308373686

In [46]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

best_rf_reg = grid_search_rf.best_estimator_

y_pred_rf_tuned = best_rf_reg.predict(X_test)

mae = mean_absolute_error(y_reg_test, y_pred_rf_tuned)
mse = mean_squared_error(y_reg_test, y_pred_rf_tuned)
rmse = np.sqrt(mse)
r2 = r2_score(y_reg_test, y_pred_rf_tuned)

print("Tuned Random Forest Regression Results")
print("--------------------------------------")
print("MAE :", mae)
print("MSE :", mse)
print("RMSE:", rmse)
print("R²  :", r2)

Tuned Random Forest Regression Results
--------------------------------------
MAE : 0.7678907030374512
MSE : 1.5377002173858647
RMSE: 1.2400404095777946
R²  : 0.9234351848805255

In [47]:
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

print("\nTarget-like columns:")
for col in X_train.columns:
    if "G3" in str(col).upper() or "RESULT" in str(col).upper():
        print(col)

X_train shape: (316, 59)
X_test shape: (79, 59)

Target-like columns:

In [48]:
train_rows = set(map(tuple, X_train.values))
test_rows = set(map(tuple, X_test.values))

overlap = train_rows.intersection(test_rows)

print("Overlapping rows:", len(overlap))

Overlapping rows: 0

In [49]:
print("Training target counts:")
print(y_cls_train.value_counts())

print("\nTesting target counts:")
print(y_cls_test.value_counts())

Training target counts:
result
1    212
0    104
Name: count, dtype: int64

Testing target counts:
result
1    53
0    26
Name: count, dtype: int64

In [50]:
raw_df = pd.read_csv("../dataset/student-mat.csv", sep=";")

raw_df["result_check"] = (raw_df["G3"] >= 10).astype(int)

print("Original G3 range:")
print(raw_df["G3"].min(), "to", raw_df["G3"].max())

print("\nResult counts:")
print(raw_df["result_check"].value_counts())

print("\nTarget consistency:")
print((raw_df["result_check"] == (raw_df["G3"] >= 10).astype(int)).all())

Original G3 range:
0 to 20

Result counts:
result_check
1    265
0    130
Name: count, dtype: int64

Target consistency:
True

In [51]:
X_train_no_grades = X_train.drop(columns=["31", "32"], errors="ignore")
X_test_no_grades = X_test.drop(columns=["31", "32"], errors="ignore")

print("Original features:", X_train.shape)
print("Without G1/G2:", X_train_no_grades.shape)

Original features: (316, 59)
Without G1/G2: (316, 57)

In [52]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

lr_no_grades = LogisticRegression(max_iter=1000, random_state=42)

lr_no_grades.fit(X_train_no_grades, y_cls_train)

y_pred_no_grades = lr_no_grades.predict(X_test_no_grades)

print("Accuracy :", accuracy_score(y_cls_test, y_pred_no_grades))
print("Precision:", precision_score(y_cls_test, y_pred_no_grades))
print("Recall   :", recall_score(y_cls_test, y_pred_no_grades))
print("F1 Score :", f1_score(y_cls_test, y_pred_no_grades))

print("\nConfusion Matrix:")
print(confusion_matrix(y_cls_test, y_pred_no_grades))

Accuracy : 1.0
Precision: 1.0
Recall   : 1.0
F1 Score : 1.0

Confusion Matrix:
[[26  0]
 [ 0 53]]

In [53]:
print(X_train_no_grades.head())
print(X_train_no_grades.dtypes.value_counts())
print("Number of features:", X_train_no_grades.shape[1])

          0         1         2         3         4         5         6  \
0 -1.305332  1.135587  0.462701  0.722867  2.386735 -0.442589 -2.091898
1 -0.524111 -0.667656 -1.388103  2.115708 -1.262660 -0.442589  0.093357
2 -1.305332 -1.569278 -1.388103  2.115708 -1.262660 -0.442589  0.093357
3  1.819554  0.233965 -0.462701 -0.669974 -1.262660  3.553358  0.093357
4  1.038332  1.135587  1.388103  2.115708 -1.262660 -0.442589  0.093357

          7         8         9  ...   49   50   51   52   53   54   55   56  \
0 -1.272747 -1.038594 -0.554434  ...  1.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0
1 -0.269784 -0.136957 -0.554434  ...  1.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0
2 -0.269784 -0.136957 -0.554434  ...  0.0  1.0  1.0  0.0  0.0  1.0  0.0  1.0
3  1.736141  0.764679 -0.554434  ...  1.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0
4  0.733178 -0.136957  0.513866  ...  0.0  1.0  0.0  1.0  0.0  1.0  0.0  1.0

    57   58
0  1.0  0.0
1  1.0  0.0
2  0.0  1.0
3  0.0  1.0
4  0.0  1.0

[5 rows x 57 columns]
float64    57
Name: count, dtype: int64
Number of features: 57

In [54]:
import pandas as pd

check = pd.DataFrame(X_train_no_grades)
check["result"] = y_cls_train.values

correlations = check.corr()["result"].drop("result").abs().sort_values(ascending=False)

print(correlations.head(10))

15    1.000000
14    0.728317
13    0.677173
5     0.389703
54    0.191138
53    0.191138
8     0.171252
0     0.137991
43    0.122545
44    0.122545
Name: result, dtype: float64

In [55]:
import pandas as pd

# Load original dataset
df = pd.read_csv("../dataset/student-mat.csv", sep=";")

# Create classification target
df["result"] = (df["G3"] >= 10).astype(int)

# Create input features
X = df.drop(["G3", "result"], axis=1)

print("Original feature columns:")
print(X.columns.tolist())

Original feature columns:
['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu', 'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime', 'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences', 'G1', 'G2']

In [56]:
print("Processed feature 5:")
print(preprocessor.get_feature_names_out()[5])
print("Feature 5 values:")
print(X_train_no_grades["5"].value_counts())

Processed feature 5:
num__failures
Feature 5 values:
5
-0.442589    251
 0.889393     39
 3.553358     14
 2.221376     12
Name: count, dtype: int64

In [57]:
print("y_cls_train first 10:")
print(y_cls_train.head(10).to_list())

print("\nFeature 5 first 10:")
print(X_train_no_grades["5"].head(10).to_list())

print("\nCorrelation:")
print(X_train_no_grades["5"].corr(y_cls_train))
print("Failures from original dataset:")
print(X["failures"].value_counts())

print("\nClassification target:")
print(df["result"].value_counts())

y_cls_train first 10:
[0, 1, 0, 0, 0, 1, 1, 1, 1, 1]

Feature 5 first 10:
[-0.4425890653333237, -0.4425890653333237, -0.4425890653333237, 3.5533579245332563, -0.4425890653333237, -0.4425890653333237, -0.4425890653333237, -0.4425890653333237, -0.4425890653333237, -0.4425890653333237]

Correlation:
-0.3897032711955368
Failures from original dataset:
failures
0    312
1     50
2     17
3     16
Name: count, dtype: int64

Classification target:
result
1    265
0    130
Name: count, dtype: int64

In [58]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

models = {
    "Logistic Regression": LogisticRegression(max_iter=1000, random_state=42),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(n_estimators=100, random_state=42),
    "XGBoost": XGBClassifier(
        n_estimators=100,
        max_depth=3,
        learning_rate=0.1,
        random_state=42,
        eval_metric="logloss"
    )
}

results = {}

for name, model in models.items():
    model.fit(X_train, y_cls_train)
    pred = model.predict(X_test)

    results[name] = {
        "Accuracy": accuracy_score(y_cls_test, pred),
        "Precision": precision_score(y_cls_test, pred),
        "Recall": recall_score(y_cls_test, pred),
        "F1": f1_score(y_cls_test, pred)
    }

results_df = pd.DataFrame(results).T
print(results_df)

                     Accuracy  Precision  Recall   F1
Logistic Regression       1.0        1.0     1.0  1.0
Decision Tree             1.0        1.0     1.0  1.0
Random Forest             1.0        1.0     1.0  1.0
XGBoost                   1.0        1.0     1.0  1.0

In [59]:
import joblib
import os

os.makedirs("../models", exist_ok=True)

classification_model = models["Random Forest"]

joblib.dump(classification_model, "../models/classification_model.pkl")
joblib.dump(best_rf_reg, "../models/regression_model.pkl")

print("Models saved successfully!")

Models saved successfully!